<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.finos.legend.depot</groupId>
        <artifactId>legend-depot</artifactId>
        <version>2.65.1-SNAPSHOT</version>
    </parent>

    <groupId>org.finos.legend.depot</groupId>
    <artifactId>legend-depot-mutation-aggregation</artifactId>
    <version>2.65.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-model</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-pure-model-context</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-store-mongo</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-core-schedules-api</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-core-schedules</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-core-schedules-store-mongo</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-metrics-query-api</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-core-tracing</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-core-authorisation</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-artifacts-api</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-artifacts-store-mongo</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-artifacts-services</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-artifacts-repository-api</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-artifacts-repository-maven-impl</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-servers-common</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-server</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-store-server</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-core-store-api</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-notifications-services</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.finos.legend.depot</groupId>
            <artifactId>legend-depot-notifications-store-mongo</artifactId>
            <version>2.65.1-SNAPSHOT</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <executions>
                    <execution>
                        <id>run-mutation-tests</id>
                        <phase>none</phase>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>report-aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>